from setuptools import setup, find_packages

setup(
    name="tcr",
    version="0.1.0",
    description="Transparent Conflict Resolution in Retrieval-Augmented Generation",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="TCR Team",
    author_email="",
    url="https://github.com/your-repo/tcr",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.40.0",
        "accelerate>=0.27.0",
        "datasets>=2.18.0",
        "sentencepiece>=0.1.99",
        "protobuf>=4.25.0",
        "wandb>=0.16.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "scikit-learn>=1.4.0",
        "pandas>=2.0.0",
        "tqdm>=4.66.0",
        "pyyaml>=6.0.0",
        "python-dotenv>=1.0.0",
        "rich>=13.7.0",
    ],
    extras_require={
        "flash-attn": [
            "flash-attn>=2.5.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
